version: "3.8"
services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - laravel

  laravel_webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "8097:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    networks:
      - laravel

  laravel_redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6380:6379" # use different port to avoid conflict
    networks:
      - laravel

  laravel_db:
    image: mysql:8
    container_name: laravel_db
    ports:
      - "3307:3306" # different from host's 3306
    environment:
      MYSQL_DATABASE: gm58_hr
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - laravel_dbdata:/var/lib/mysql
    networks:
      - laravel

  laravel_queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    depends_on:
      - laravel_app
    networks:
      - laravel

  laravel_scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_scheduler
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    volumes:
      - ./:/var/www
    depends_on:
      - laravel_app
    networks:
      - laravel

  laravel_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    ports:
      - "8098:80"
    environment:
      PMA_HOST: laravel_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - laravel_db
    networks:
      - laravel

  laravel_redis_ui:
    image: rediscommander/redis-commander:latest
    container_name: laravel_redis_ui
    ports:
      - "8083:8081"
    environment:
      - REDIS_HOSTS=local:laravel_redis:6379
    depends_on:
      - laravel_redis
    networks:
      - laravel

networks:
  laravel:

volumes:
  laravel_dbdata:

